import type { Product } from './types';

export const STATIC_PRODUCTS: Product[] = [
  {
    id: 'lounge-chair',
    sku: 'RWQ-LC-001',
    nameAr: 'كرسي لاونج',
    nameEn: 'Lounge Chair',
    descriptionAr: 'كرسي بين باج فاخر بتصميم لاونج مريح، مقاس 90×99×60 سم',
    descriptionEn: 'Premium bean bag with lounge chair design, 90×99×60 cm',
    longDescriptionAr: 'كرسي اللاونج من رواقة — تصميم فريد يجمع بين راحة البين باج وأناقة الكرسي. مصنوع من جلد صناعي فاخر. مقاييس 90×99×60 سم. مثالي لغرف المعيشة.',
    longDescriptionEn: 'The Rawaqa Lounge Chair — unique design combining bean bag comfort with armchair elegance. Premium faux leather. 90×99×60cm. Perfect for living rooms.',
    price: 1815,
    compareAtPrice: 2100,
    images: [
      '/products/lounge-chair/c06c5049-6ff5-46e5-91fc-fe4c697ba088.jpg',
      '/products/lounge-chair/ChatGPT Image Sep 5, 2026, 12_32_34 AM.jpg',
    ],
    category: { id: 'relax', nameAr: 'استرخاء', nameEn: 'Relax', slug: 'relax' },
    inventory: { onHandQuantity: 25, reservedQuantity: 0, availableQuantity: 25, lowStockThreshold: 5 },
    featured: true,
    status: 'active',
    createdAt: '2026-09-01T00:00:00Z',
  },
  {
    id: '8ball-bean-bag',
    sku: 'RWQ-8B-001',
    nameAr: 'بين باج 8-بول',
    nameEn: '8-Ball Bean Bag',
    descriptionAr: 'بين باج على شكل كرة البلياردو، مقاس 2XL — يتحمل حتى 120 كجم',
    descriptionEn: 'Billiard ball-shaped bean bag, size 2XL — holds up to 120 kg',
    longDescriptionAr: 'تصميم مميز على شكل كرة البلياردو. مقاس 2XL — 99×90×55 سم، يتحمل حتى 120 كجم. جلد صناعي سهل التنظيف.',
    longDescriptionEn: 'Unique billiard ball design. Size 2XL — 99×90×55cm, capacity 120kg. Easy-clean faux leather.',
    price: 1650,
    compareAtPrice: 1950,
    images: [
      '/products/8ball-bean-bag/img-1.jpg',
      '/products/8ball-bean-bag/img-2.jpg',
      '/products/8ball-bean-bag/img-3.jpg',
      '/products/8ball-bean-bag/img-4.jpg',
    ],
    category: { id: 'kids', nameAr: 'أطفال', nameEn: 'Kids', slug: 'kids' },
    inventory: { onHandQuantity: 40, reservedQuantity: 0, availableQuantity: 40, lowStockThreshold: 8 },
    featured: true,
    status: 'active',
    createdAt: '2026-09-01T00:00:00Z',
  },
  {
    id: 'football-bean-bag-l',
    sku: 'RWQ-FB-L',
    nameAr: 'بين باج كورة — مقاس L',
    nameEn: 'Football Bean Bag — Size L',
    descriptionAr: 'بين باج على شكل كرة القدم — مقاس L',
    descriptionEn: 'Football-shaped bean bag — Size L',
    longDescriptionAr: 'بين باج كورة القدم — جلد أسود وأبيض. متوفر بـ 4 مقاسات.',
    longDescriptionEn: 'Football bean bag — black and white faux leather. Available in 4 sizes.',
    price: 1270,
    compareAtPrice: 1500,
    images: [
      '/products/football-bean-bag/img-1.jpg',
      '/products/football-bean-bag/img-2.jpg',
      '/products/football-bean-bag/img-3.jpg',
      '/products/football-bean-bag/img-4.jpg',
      '/products/football-bean-bag/img-5.jpg',
      '/products/football-bean-bag/img-6.jpg',
      '/products/football-bean-bag/img-7.jpg',
      '/products/football-bean-bag/img-8.jpg',
      '/products/football-bean-bag/img-9.jpg',
      '/products/football-bean-bag/img-10.jpg',
      '/products/football-bean-bag/img-11.jpg',
      '/products/football-bean-bag/img-12.jpg',
      '/products/football-bean-bag/img-13.jpg',
      '/products/football-bean-bag/img-14.jpg',
      '/products/football-bean-bag/img-15.jpg',
      '/products/football-bean-bag/img-16.jpg',
      '/products/football-bean-bag/img-17.jpg',
    ],
    category: { id: 'kids', nameAr: 'أطفال', nameEn: 'Kids', slug: 'kids' },
    inventory: { onHandQuantity: 50, reservedQuantity: 0, availableQuantity: 50, lowStockThreshold: 10 },
    featured: true,
    status: 'active',
    createdAt: '2026-09-01T00:00:00Z',
  },
  {
    id: 'football-bean-bag-xl',
    sku: 'RWQ-FB-XL',
    nameAr: 'بين باج كورة — مقاس XL',
    nameEn: 'Football Bean Bag — Size XL',
    descriptionAr: 'بين باج كرة القدم مقاس XL',
    descriptionEn: 'Football bean bag Size XL',
    longDescriptionAr: 'بين باج كورة القدم — مقاس XL.',
    longDescriptionEn: 'Football Bean Bag — XL size.',
    price: 1430,
    compareAtPrice: 1700,
    images: [
      '/products/football-bean-bag/img-7.jpg',
      '/products/football-bean-bag/img-8.jpg',
      '/products/football-bean-bag/img-9.jpg',
    ],
    category: { id: 'kids', nameAr: 'أطفال', nameEn: 'Kids', slug: 'kids' },
    inventory: { onHandQuantity: 35, reservedQuantity: 0, availableQuantity: 35, lowStockThreshold: 8 },
    featured: false,
    status: 'active',
    createdAt: '2026-09-01T00:00:00Z',
  },
  {
    id: 'football-bean-bag-2xl',
    sku: 'RWQ-FB-2XL',
    nameAr: 'بين باج كورة — مقاس 2XL',
    nameEn: 'Football Bean Bag — Size 2XL',
    descriptionAr: 'بين باج كرة القدم مقاس 2XL',
    descriptionEn: 'Football bean bag Size 2XL',
    longDescriptionAr: 'بين باج كورة القدم — مقاس 2XL.',
    longDescriptionEn: 'Football Bean Bag — 2XL size.',
    price: 1610,
    compareAtPrice: 1900,
    images: [
      '/products/football-bean-bag/img-10.jpg',
      '/products/football-bean-bag/img-11.jpg',
      '/products/football-bean-bag/img-12.jpg',
    ],
    category: { id: 'kids', nameAr: 'أطفال', nameEn: 'Kids', slug: 'kids' },
    inventory: { onHandQuantity: 30, reservedQuantity: 0, availableQuantity: 30, lowStockThreshold: 8 },
    featured: false,
    status: 'active',
    createdAt: '2026-09-01T00:00:00Z',
  },
  {
    id: 'football-bean-bag-3xl',
    sku: 'RWQ-FB-3XL',
    nameAr: 'بين باج كورة — مقاس 3XL',
    nameEn: 'Football Bean Bag — Size 3XL',
    descriptionAr: 'بين باج كرة القدم مقاس 3XL',
    descriptionEn: 'Football bean bag Size 3XL',
    longDescriptionAr: 'بين باج كورة القدم — مقاس 3XL الأكبر.',
    longDescriptionEn: 'Football Bean Bag — largest 3XL size.',
    price: 1920,
    compareAtPrice: 2200,
    images: [
      '/products/football-bean-bag/img-13.jpg',
      '/products/football-bean-bag/img-14.jpg',
      '/products/football-bean-bag/img-15.jpg',
      '/products/football-bean-bag/img-16.jpg',
    ],
    category: { id: 'kids', nameAr: 'أطفال', nameEn: 'Kids', slug: 'kids' },
    inventory: { onHandQuantity: 20, reservedQuantity: 0, availableQuantity: 20, lowStockThreshold: 5 },
    featured: false,
    status: 'active',
    createdAt: '2026-09-01T00:00:00Z',
  },
  {
    id: 'chair-lounge',
    sku: 'RWQ-CHL-001',
    nameAr: 'كرسي لاونج مخمل + فوتة',
    nameEn: 'Chair Lounge + Ottoman',
    descriptionAr: 'كرسي بين باج مخمل فاخر مع فوتة، 110×110×90 سم',
    descriptionEn: 'Premium velvet bean bag chair with ottoman, 110×110×90 cm',
    longDescriptionAr: 'طقم كرسي لاونج المخمل — قماش مخمل فاخر مع فوتة مطابقة. الأبعاد 110×110×90 سم.',
    longDescriptionEn: 'Rawaqa Velvet Chair Lounge Set — luxurious velvet with matching ottoman. 110×110×90cm.',
    price: 1920,
    compareAtPrice: 2300,
    images: [
      '/products/lounge-chair/c06c5049-6ff5-46e5-91fc-fe4c697ba088.jpg',
      '/products/lounge-chair/ChatGPT Image Sep 5, 2026, 12_32_34 AM.jpg',
    ],
    category: { id: 'relax', nameAr: 'استرخاء', nameEn: 'Relax', slug: 'relax' },
    inventory: { onHandQuantity: 20, reservedQuantity: 0, availableQuantity: 20, lowStockThreshold: 4 },
    featured: true,
    status: 'active',
    createdAt: '2026-09-01T00:00:00Z',
  },
  {
    id: 'lounge-chair-classic',
    sku: 'RWQ-LC-002',
    nameAr: 'كرسي لاونج كلاسيك',
    nameEn: 'Classic Lounge Chair',
    descriptionAr: 'كرسي لاونج كلاسيك بألوان متعددة، 90×99×60 سم',
    descriptionEn: 'Classic lounge bean bag in multiple colors, 90×99×60 cm',
    longDescriptionAr: 'كرسي اللاونج الكلاسيك — تصميم خالد يناسب جميع الديكورات. 90×99×60 سم.',
    longDescriptionEn: 'Classic Lounge Chair — timeless design for all decors. 90×99×60cm.',
    price: 1815,
    compareAtPrice: 2100,
    images: [
      '/products/lounge-chair/ChatGPT Image Sep 5, 2026, 12_32_34 AM.jpg',
      '/products/lounge-chair/c06c5049-6ff5-46e5-91fc-fe4c697ba088.jpg',
    ],
    category: { id: 'relax', nameAr: 'استرخاء', nameEn: 'Relax', slug: 'relax' },
    inventory: { onHandQuantity: 30, reservedQuantity: 0, availableQuantity: 30, lowStockThreshold: 5 },
    featured: false,
    status: 'active',
    createdAt: '2026-09-01T00:00:00Z',
  },
];

export const STATIC_CATEGORIES = [
  { id: 'relax',   nameAr: 'استرخاء', nameEn: 'Relax',   slug: 'relax',   status: 'active' as const },
  { id: 'game',    nameAr: 'ألعاب',   nameEn: 'Game',    slug: 'game',    status: 'active' as const },
  { id: 'kids',    nameAr: 'أطفال',   nameEn: 'Kids',    slug: 'kids',    status: 'active' as const },
  { id: 'outdoor', nameAr: 'خارجي',  nameEn: 'Outdoor', slug: 'outdoor', status: 'active' as const },
];
