import type { Product } from './types';

// Static fallback data — mirrors the real DB.
// Used when API is unreachable (dev offline / first load).

export const STATIC_PRODUCTS: Product[] = [
  {
    id: 'chair-lounge',
    sku: 'RWQ-CHL-001',
    nameAr: 'كرسي لاونج',
    nameEn: 'Chair Lounge',
    descriptionAr: 'كرسي لاونج فاخر — 110×110×90 سم',
    descriptionEn: 'Premium Chair Lounge — 110×110×90 cm',
    longDescriptionAr: 'كرسي اللاونج من رواقة — تصميم أنيق يجمع بين الراحة والفخامة. الأبعاد: 110 سم × 110 سم × 90 سم.',
    longDescriptionEn: 'Rawaqa Chair Lounge — elegant design combining comfort and luxury. Dimensions: 110×110×90 cm.',
    price: 1920,
    compareAtPrice: 2300,
    images: [
      '/products/chair-lounge-new/img-1.jpg',
      '/products/chair-lounge-new/img-2.jpg',
      '/products/chair-lounge-new/img-3.jpg',
    ],
    category: { id: 'relax', nameAr: 'استرخاء', nameEn: 'Relax', slug: 'relax' },
    inventory: { onHandQuantity: 20, reservedQuantity: 0, availableQuantity: 20, lowStockThreshold: 4 },
    featured: true,
    status: 'active',
    createdAt: '2026-09-01T00:00:00Z',
  },
  {
    id: '8ball-bean-bag',
    sku: 'RWQ-8B-001',
    nameAr: 'بين باج 8-بول',
    nameEn: '8-Ball Bean Bag',
    descriptionAr: 'بين باج كرة بلياردو — مقاس 2XL، 99×90×55 سم، يتحمل 120 كجم',
    descriptionEn: 'Billiard ball bean bag — Size 2XL, 99×90×55 cm, 120 kg capacity',
    longDescriptionAr: 'بين باج 8-بول من رواقة — تصميم مميز. المقاس 2XL: 99×90×55 سم. يتحمل حتى 120 كجم.',
    longDescriptionEn: 'Rawaqa 8-Ball Bean Bag — unique design. 2XL: 99×90×55 cm, 120 kg capacity.',
    price: 1650,
    compareAtPrice: 1950,
    images: [
      '/products/8ball-new/img-1.jpg',
      '/products/8ball-new/img-2.jpg',
      '/products/8ball-new/img-3.jpg',
      '/products/8ball-new/img-4.jpg',
    ],
    category: { id: 'kids', nameAr: 'أطفال', nameEn: 'Kids', slug: 'kids' },
    inventory: { onHandQuantity: 40, reservedQuantity: 0, availableQuantity: 40, lowStockThreshold: 8 },
    featured: true,
    status: 'active',
    createdAt: '2026-09-01T00:00:00Z',
  },
  {
    id: 'football-bean-bag-l',
    sku: 'RWQ-FB-L',
    nameAr: 'بين باج كورة — مقاس L',
    nameEn: 'Football Bean Bag — Size L',
    descriptionAr: 'بين باج على شكل كرة القدم — مقاس L',
    descriptionEn: 'Football-shaped bean bag — Size L',
    longDescriptionAr: 'بين باج كورة القدم — جلد أسود وأبيض. مقاس L.',
    longDescriptionEn: 'Football Bean Bag — black and white faux leather. Size L.',
    price: 1270,
    compareAtPrice: 1500,
    images: [
      '/products/football-new/img-1.jpg',
      '/products/football-new/img-2.jpg',
      '/products/football-new/img-3.jpg',
      '/products/football-new/img-4.jpg',
      '/products/football-new/img-5.jpg',
    ],
    category: { id: 'kids', nameAr: 'أطفال', nameEn: 'Kids', slug: 'kids' },
    inventory: { onHandQuantity: 50, reservedQuantity: 0, availableQuantity: 50, lowStockThreshold: 10 },
    featured: true,
    status: 'active',
    createdAt: '2026-09-01T00:00:00Z',
  },
  {
    id: 'football-bean-bag-xl',
    sku: 'RWQ-FB-XL',
    nameAr: 'بين باج كورة — مقاس XL',
    nameEn: 'Football Bean Bag — Size XL',
    descriptionAr: 'بين باج كرة القدم — مقاس XL',
    descriptionEn: 'Football bean bag — Size XL',
    longDescriptionAr: 'بين باج كورة القدم — مقاس XL.',
    longDescriptionEn: 'Football Bean Bag — Size XL.',
    price: 1430,
    compareAtPrice: 1700,
    images: [
      '/products/football-new/img-6.jpg',
      '/products/football-new/img-7.jpg',
      '/products/football-new/img-8.jpg',
      '/products/football-new/img-9.jpg',
    ],
    category: { id: 'kids', nameAr: 'أطفال', nameEn: 'Kids', slug: 'kids' },
    inventory: { onHandQuantity: 35, reservedQuantity: 0, availableQuantity: 35, lowStockThreshold: 8 },
    featured: false,
    status: 'active',
    createdAt: '2026-09-01T00:00:00Z',
  },
  {
    id: 'football-bean-bag-2xl',
    sku: 'RWQ-FB-2XL',
    nameAr: 'بين باج كورة — مقاس 2XL',
    nameEn: 'Football Bean Bag — Size 2XL',
    descriptionAr: 'بين باج كرة القدم — مقاس 2XL',
    descriptionEn: 'Football bean bag — Size 2XL',
    longDescriptionAr: 'بين باج كورة القدم — مقاس 2XL الكبير.',
    longDescriptionEn: 'Football Bean Bag — Large 2XL size.',
    price: 1610,
    compareAtPrice: 1900,
    images: [
      '/products/football-new/img-10.jpg',
      '/products/football-new/img-11.jpg',
      '/products/football-new/img-12.jpg',
      '/products/football-new/img-13.jpg',
    ],
    category: { id: 'kids', nameAr: 'أطفال', nameEn: 'Kids', slug: 'kids' },
    inventory: { onHandQuantity: 30, reservedQuantity: 0, availableQuantity: 30, lowStockThreshold: 8 },
    featured: false,
    status: 'active',
    createdAt: '2026-09-01T00:00:00Z',
  },
  {
    id: 'football-bean-bag-3xl',
    sku: 'RWQ-FB-3XL',
    nameAr: 'بين باج كورة — مقاس 3XL',
    nameEn: 'Football Bean Bag — Size 3XL',
    descriptionAr: 'بين باج كرة القدم — مقاس 3XL',
    descriptionEn: 'Football bean bag — Size 3XL',
    longDescriptionAr: 'بين باج كورة القدم — مقاس 3XL الأكبر.',
    longDescriptionEn: 'Football Bean Bag — Largest 3XL size.',
    price: 1920,
    compareAtPrice: 2200,
    images: [
      '/products/football-new/img-14.jpg',
      '/products/football-new/img-15.jpg',
      '/products/football-new/img-16.jpg',
      '/products/football-new/img-17.jpg',
    ],
    category: { id: 'kids', nameAr: 'أطفال', nameEn: 'Kids', slug: 'kids' },
    inventory: { onHandQuantity: 20, reservedQuantity: 0, availableQuantity: 20, lowStockThreshold: 5 },
    featured: false,
    status: 'active',
    createdAt: '2026-09-01T00:00:00Z',
  },
];

export const STATIC_CATEGORIES = [
  { id: 'relax',   nameAr: 'استرخاء', nameEn: 'Relax',   slug: 'relax',   status: 'active' as const },
  { id: 'game',    nameAr: 'ألعاب',   nameEn: 'Game',    slug: 'game',    status: 'active' as const },
  { id: 'kids',    nameAr: 'أطفال',   nameEn: 'Kids',    slug: 'kids',    status: 'active' as const },
  { id: 'outdoor', nameAr: 'خارجي',  nameEn: 'Outdoor', slug: 'outdoor', status: 'active' as const },
];
